name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: ['master']
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - '**/*.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'action.yml'
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - run: python -m unittest tests/test_*.py
        shell: bash

      - uses: ./
        id: current-semester
        with:
          which: current

      - run: echo ${{ steps.current-semester.name }}

      - uses: ./
        id: next-semester
        with:
          which: next

      - run: echo ${{ steps.next-semester.name }}

      - uses: ./
        id: current-semester-ws
        with:
          floor: ws

      - run: echo ${{ steps.current-semester-ws.name }}

      - uses: ./
        id: current-semester-ss
        with:
          floor: ss

      - run: echo ${{ steps.current-semester-ss.name }}